functions: "/path/to/functions.sh"
input_directory: "/path/to/directory" # directory that contains a single pair of uncompressed fasta file
output_directory: "/path/to/directory" # directory that all intermediate files and final results will be saved
barcode1: "/path/to/barcode1.fa"
barcode2: "/path/to/barcode2.fa"
barcode3: "/path/to/barcode3.fa"
primer: "/path/to/primer.fa"
reference: "/path/to/reference.fa"

# threads to use, better to be same as the specified in snakemake 
threads: 5

# prune samples based on R1+R2 reads. It can be > min_reads, or < max_reads, or between min_reads and max_reads,  
min_reads: 10 
max_reads: 

# cutadapt 
cutadapt_error_rate: 0.125
cutadapt_overlap_minlength: 6

# trimmomatic average quality with the sliding windows
trimmomatic_quality : 15
