functions: "/Users/shaodongwei/snakemake/functions.sh"
fastq1: "/Users/shaodongwei/snakemake/data/KP_R1.fastq" #specify input files 
fastq2: "/Users/shaodongwei/snakemake/data/KP_R2.fastq" 
output_directory: "/Users/shaodongwei/snakemake/output4" 
barcode1: "/Users/shaodongwei/snakemake/barcode/barcode3.fa"
barcode2: "/Users/shaodongwei/snakemake/barcode/barcode2.fa"
barcode3: "/Users/shaodongwei/snakemake/barcode/barcode1.fa"
primer: "/Users/shaodongwei/snakemake/primer/primer.fa"
reference: "/Users/shaodongwei/snakemake/reference_plas/KP_fa" # the sample name has to be "_" separated. 

# threads to use, better to be same as the specified in snakemake 
threads: 4

# prune samples based on reads 
min_reads: 10
max_reads: 

# cutadapt 
cutadapt_error_rate: 0.125
cutadapt_overlap_minlength: 8

# trimmomatic average quality with the sliding windows
trimmomatic_quality : 15